// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartService.DataAccess.DatabaseContext;

#nullable disable

namespace SmartService.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartService.Domain.Models.Employment", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<short>("CompanyID")
                        .HasColumnType("smallint");

                    b.Property<byte>("TaskListCategoryID")
                        .HasColumnType("smallint");

                    b.HasKey("UserID");

                    b.ToTable("#Employment", (string)null);
                });

            modelBuilder.Entity("SmartService.Domain.Models.ListCategory", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("smallint");

                    b.Property<short>("PermissionExtID")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.ToTable("ListCategories");
                });

            modelBuilder.Entity("SmartService.Domain.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ApprovalWith")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Archived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssetID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalatedTo")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<short>("WorkTypeID")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SmartService.Domain.Models.TaskResponsibleUser", b =>
                {
                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TaskID", "UserID");

                    b.ToTable("#TaskResponsibleUser", (string)null);
                });

            modelBuilder.Entity("SmartService.Domain.Models.TaskUserCache", b =>
                {
                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<byte>("TaskListCategoryID")
                        .HasColumnType("smallint");

                    b.HasKey("TaskID", "UserID", "TaskListCategoryID");

                    b.ToTable("#TaskUserCacheADM", (string)null);
                });

            modelBuilder.Entity("SmartService.Domain.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartService.Domain.Models.UserTaskListCategory", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<byte>("TaskListCategoryID")
                        .HasColumnType("smallint");

                    b.HasKey("UserID", "TaskListCategoryID");

                    b.ToTable("#UserTaskListCategory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
